# Generated by Django 5.0.7 on 2024-08-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
