# Generated by Django 5.0.7 on 2024-08-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todolist_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
