# Generated by Django 5.0.7 on 2024-08-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_todolist_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
