# Generated by Django 5.0.7 on 2024-08-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_todolist_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='list',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
