# Generated by Django 5.0.7 on 2024-08-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_todolist_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='type',
            field=models.CharField(choices=[('personal', 'PERSONAL'), ('Shopping', 'SHOPPING'), ('wishlist', 'WISHLIST'), ('work', 'WORK')], default='personal', max_length=10, null=True),
        ),
    ]
